name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup database
        run: |
          mkdir -p alembic/versions
          export DATABASE_URL=sqlite+aiosqlite:///test_database.db
          alembic revision --autogenerate -m "create initial schema" || true
          alembic upgrade head

      - name: Run tests
        env:
          DATABASE_URL: sqlite+aiosqlite:///test_database.db
          API_KEY: ${{ secrets.API_KEY }}
        run: pytest
